diff --git a/dos2unix/Makefile b/dos2unix/Makefile
index fb93362..dcd31a0 100644
--- a/dos2unix/Makefile
+++ b/dos2unix/Makefile
@@ -378,16 +378,16 @@ status:
 	@echo "LIBS         = $(LIBS)"
 
 common.o : common.c common.h dos2unix.h unix2dos.h version.mk
-	$(CC) $(DEFS) $(EXTRA_CFLAGS) $(DOS2UNIX_NLSDEFS) $(CFLAGS) -c $< -o $@
+	$(CC) $(DEFS) $(EXTRA_CFLAGS) $(DOS2UNIX_NLSDEFS) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
 
 querycp.o : querycp.c querycp.h
-	$(CC) $(DEFS) $(EXTRA_CFLAGS) $(DOS2UNIX_NLSDEFS) $(CFLAGS) -c $< -o $@
+	$(CC) $(DEFS) $(EXTRA_CFLAGS) $(DOS2UNIX_NLSDEFS) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
 
 dos2unix.o : dos2unix.c dos2unix.h querycp.h common.h
-	$(CC) $(DEFS) $(EXTRA_CFLAGS) $(DOS2UNIX_NLSDEFS) $(CFLAGS) -c $< -o $@
+	$(CC) $(DEFS) $(EXTRA_CFLAGS) $(DOS2UNIX_NLSDEFS) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
 
 unix2dos.o : unix2dos.c unix2dos.h querycp.h common.h
-	$(CC) $(DEFS) $(EXTRA_CFLAGS) $(DOS2UNIX_NLSDEFS) $(CFLAGS) -c $< -o $@
+	$(CC) $(DEFS) $(EXTRA_CFLAGS) $(DOS2UNIX_NLSDEFS) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
 
 $(BIN): dos2unix.o querycp.o common.o
 	$(CC) $+ $(LDFLAGS) $(LIBS) -o $@
